// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAQFs6r-zHW2fjbWh953Z2CjQsTloMDIOE',
    appId: '1:458837247991:web:4c89bfbff4be3019ca90f2',
    messagingSenderId: '458837247991',
    projectId: 'idletamergame',
    authDomain: 'idletamergame.firebaseapp.com',
    databaseURL: 'https://idletamergame-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'idletamergame.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBcMCjoslqR6A09t6LFdyvn8GDtv9KpbGQ',
    appId: '1:458837247991:android:fecbd3d1d4727d3eca90f2',
    messagingSenderId: '458837247991',
    projectId: 'idletamergame',
    databaseURL: 'https://idletamergame-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'idletamergame.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAjGA68Uyd0bgrPFRJ7yLNawEm1mI6ovNo',
    appId: '1:458837247991:ios:cd6ee0c74ba9a6e4ca90f2',
    messagingSenderId: '458837247991',
    projectId: 'idletamergame',
    databaseURL: 'https://idletamergame-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'idletamergame.firebasestorage.app',
    iosBundleId: 'com.example.idletamergame',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAjGA68Uyd0bgrPFRJ7yLNawEm1mI6ovNo',
    appId: '1:458837247991:ios:cd6ee0c74ba9a6e4ca90f2',
    messagingSenderId: '458837247991',
    projectId: 'idletamergame',
    databaseURL: 'https://idletamergame-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'idletamergame.firebasestorage.app',
    iosBundleId: 'com.example.idletamergame',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAQFs6r-zHW2fjbWh953Z2CjQsTloMDIOE',
    appId: '1:458837247991:web:2f4c36b19c667d20ca90f2',
    messagingSenderId: '458837247991',
    projectId: 'idletamergame',
    authDomain: 'idletamergame.firebaseapp.com',
    databaseURL: 'https://idletamergame-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'idletamergame.firebasestorage.app',
  );
}
